apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- campaigns-deployment.yaml
- campaigns-service.yaml

labels:
- includeSelectors: true
  pairs:
    app: campaigns
