apiVersion: v1
kind: Service
metadata:
  name: campaigns
spec:
  type: NodePort
  selector:
    app: campaigns 
  ports:
  - port: 3000          # The port exposed by the service
    targetPort: 3000    # The port your app is running on in the container
    nodePort: 30080     # Port accessible from outside (must be 30000-32767)
