apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  finalizers: []
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
