apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432    # The port your app is running on in the container
      nodePort: 30432     # Port accessible from outside (must be 30000-32767)
  selector:
    app: postgres
